// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/inventory": {
    params: {};
  };
  "/sales": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/inventory" | "/sales";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/inventory.tsx": {
    id: "routes/inventory";
    page: "/inventory";
  };
  "routes/sales.tsx": {
    id: "routes/sales";
    page: "/sales";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/inventory": typeof import("./app/routes/inventory.tsx");
  "routes/sales": typeof import("./app/routes/sales.tsx");
};